# spring.datasource.url=jdbc:mysql://localhost:3306/estatebasic
# spring.datasource.username=root
# spring.datasource.password=chien1207
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8082

#Cac thao tac voi DB
spring.jpa.hibernate.ddl-auto = none
#spring.jpa.hibernate.ddl-auto = create
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.hibernate.ddl-auto = create-drop

#Chi dinh loai DB du dung, tùy vào DB mà chọn dialect cho phù hợp( mysql, oraclce )
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
#Cap quyen thao tac voi DB
spring.jpa.properties.hibernate.enable_lazy_load_no_trans = true

spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true

#Chi dinh  moi truong
spring.profiles.active = uat